### ISSUE TITLE
Meetup #23

### ISSUE THREAD

**Issue by kentaro-m** [kanazawa-js/kanazawa-js.github.io#100]
## 日程

- 2022/09/24  14:00 ~ 17:00

## 会場

- Discord（オンライン）
  - Slack の #meetup でチャット
  - Discord の もくもく部屋（ボイスチャンネル） でボイチャする

## 開催までのTODO

うえから順番にやる

### 3週間前

- [x] Connpassイベントページの作成
  - 前回のイベントをコピーして生成する
- [x] Connpassで1週間前と1日前のメッセージを投稿予約する
  - connpassのメッセージは[お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に
- [x] コミュニティページの再デプロイ
  - conppassのイベントページを公開後、vercelの`kanazawa-js.github.io`を再デプロイする
- [x] Slackの#generalなて次回イベントの通知をする
  - [お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に
- [x] [Buffer](https://publish.buffer.com/profile/5f44c0bf8c68015ea35d9413/tab/queue)でTwitterPostをスケジューリング（3週間前・2週間前・1週間前・前日・当日）
  - 告知内容は[お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に

## 当日

- [ ] イベントのファシリテート対応
  - [こちらを確認しながら進行する！](https://github.com/kanazawa-js/community-page/wiki/%E3%83%95%E3%82%A1%E3%82%B7%E3%83%AA%E3%83%86%E3%83%BC%E3%83%88%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)

**Comment by yu-kgr** [comment]
1. イベント公開しました。

https://kanazawajs.connpass.com/event/257719/

---

メッセージの投稿予約をしました。

![image](https://user-images.githubusercontent.com/6540072/188341099-cd1e2246-28b2-4f41-9e94-f45f06ea17ae.png)

---

Bufferの対応を完了しました。

![image](https://user-images.githubusercontent.com/6540072/188341915-e7bd9c3f-95ec-4ee4-a9f5-644cae4bb6f9.png)

**Comment by yu-kgr** [comment]
### コミュニティページの再デプロイ

- 対応中です。
    - https://github.com/kanazawa-js/kanazawa-js.github.io/runs/8180703303?check_suite_focus=true

**Comment by yu-kgr** [comment]
再デプロイが完了していることを確認。
checkいれます。
