### ISSUE TITLE
Meetup Todos #18

### ISSUE THREAD

**Issue by yu-kgr** [kanazawa-js/kanazawa-js.github.io#69]
## 日程

- 2022/02/26  14:00 ~ 17:00

## 会場

- Discord（オンライン）
  - Slack の #meetup でチャット
  - Discord の もくもく部屋（ボイスチャンネル） でボイチャする

## 開催までのTODO

うえから順番にやる

### 3週間前

- [x] Connpassイベントページの作成
  - 前回のイベントをコピーして生成する
- [x] Connpassで1週間前と1日前のメッセージを投稿予約する
  - connpassのメッセージは[お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に
- [x] コミュニティページの再デプロイ
  - conppassのイベントページを公開後、vercelの`kanazawa-js.github.io`を再デプロイする
- [x] Slackの#generalなて次回イベントの通知をする
  - [お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に
- [x] [Buffer](https://publish.buffer.com/profile/5f44c0bf8c68015ea35d9413/tab/queue)でTwitterPostをスケジューリング（3週間前・2週間前・1週間前・前日・当日）
  - 告知内容は[お知らせ文言テンプレ](https://github.com/kanazawa-js/community-page/wiki/%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B%E6%96%87%E8%A8%80%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)を参考に

## 当日

- [x] イベントのファシリテート対応
  - [こちらを確認しながら進行する！](https://github.com/kanazawa-js/community-page/wiki/%E3%83%95%E3%82%A1%E3%82%B7%E3%83%AA%E3%83%86%E3%83%BC%E3%83%88%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC)

**Comment by yu-kgr** [comment]
@kentaro-m @tom-256 

イベントページのプレビューを用意しました。
問題なければ公開したいと思うのでご確認お願いしますー！
https://kanazawajs.connpass.com/event/238698/preview/

**Comment by kentaro-m** [comment]
@yu-kgr 
特に問題ないと思いました。

@tom-256 
来月で何か企画します？スピードハッカソンやるみたいな話ししてましたが

**Comment by yu-kgr** [comment]
ではこちら公開しますー！

次回、なにかしら挟むのであれば別途記載内容に調整が必要っすね。

**Comment by yu-kgr** [comment]
対応しました。

>Connpassで1週間前と1日前のメッセージを投稿予約する
![image](https://user-images.githubusercontent.com/6540072/152624051-2fbbfece-b81f-4b0f-ac3b-e9dba4092ee7.png)

**Comment by yu-kgr** [comment]
セット完了。
>[Buffer](https://publish.buffer.com/profile/5f44c0bf8c68015ea35d9413/tab/queue)でTwitterPostをスケジューリング（3週間前・2週間前・1週間前・前日・当日）
![image](https://user-images.githubusercontent.com/6540072/152624655-61480050-940e-42e5-a4f6-402c6cfa1316.png)
