### ISSUE TITLE
コミュニティページをGitHub Pagesに移行する

### ISSUE THREAD

**Issue by kentaro-m** [kanazawa-js/kanazawa-js.github.io#74]
https://github.com/kanazawa-js/community-page/issues/70 の対応として、コミュニティページをGitHub Pagesに移行してください。

**Comment by yu-kgr** [comment]
Github Pagesをリリース完了したら、vercel側にリダイレクトをいれても良さそうです。
（調べたら出てきた）

https://mykii.blog/vercel-redirects-301-308/

**Comment by kentaro-m** [comment]
@yu-kgr @tom-256 
GitHub Pagesに移行が完了したので、Vercelと本リポジトリの連携を解除しました。
今後はVercelにデプロイされなくなると思います。

なお、Vercelのドメインにアクセスした場合はGitHub Pagesにリダイレクトされます。
